name: Run Repbox

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env: 
      MYSECRET: ${{ secrets.mysecret }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t skranz/gha_test .
    - name: Docker Run Action
      run: docker run --rm --name gha_test  --mount=type=secret,id=MYSECRET -v $GITHUB_WORKSPACE/output:/root/output:rw -v $GITHUB_WORKSPACE/scripts/:/root/scripts/:rw skranz/gha_test R -e 'source("~/scripts/run_test.R")'
    - uses: actions/upload-artifact@v3
      with:
        name: repbox_results
        path: ${{ github.workspace }}/output