name: Run Repbox

on:
  on:
    workflow_dispatch:
#  push:
#    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t skranz/gha_test .
    - name: Docker Run Action
      run: docker run --rm --name gha_test --env MYSECRET=${{ secrets.MYSECRET }} --env MYSECRET2=${{ secrets.MYSECRET2 }} -v $GITHUB_WORKSPACE/output:/root/output:rw -v $GITHUB_WORKSPACE/scripts/:/root/scripts/:rw skranz/gha_test R -e 'source("~/scripts/run_test.R")'
    - uses: actions/upload-artifact@v3
      with:
        name: repbox_results
        path: ${{ github.workspace }}/output